# Generated by Django 4.0.6 on 2022-07-28 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0017_alter_super_super_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super',
            name='super_type',
        ),
    ]
